name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Copy .env
        run: |
          cp .env.example .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=laravel" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=secret" >> .env
        working-directory: laravel

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        working-directory: laravel

      - name: Generate Key
        run: php artisan key:generate
        working-directory: laravel

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        working-directory: laravel

      - name: Run Migrations
        run: php artisan migrate --no-interaction --force
        working-directory: laravel

      # - name: Execute Tests
      #   run: vendor/bin/phpunit
      #   working-directory: laravel
